spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oops?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db-username}
    password: ${db-password}

  jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
          ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          show_sql: true

  # 콘솔 색상 출력을 위함
  output:
    ansi:
      enabled: always

  # 이메일 발송 관련 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-username}
    password: ${mail-password}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          timeout: 50000  # SMTP 서버에 연결 시도 후 응답을 기다리는 시간 (50,000ms)
          starttls:
            enable: true

  # redis 설정
  redis:
    host: localhost
    port: 6379

# 에러 메시지 표출을 위함
server:
  error:
    include-message: always

# 로그 레벨 설정
logging:
  level:
    com.oops.server: debug