spring:
  config:
    import: application-secrete.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
          ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          show_sql: true

  # 콘솔 색상 출력을 위함
  output:
    ansi:
      enabled: always

  # 이메일 발송 관련 설정
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          timeout: 50000  # SMTP 서버에 연결 시도 후 응답을 기다리는 시간 (50,000ms)
          starttls:
            enable: true

# 에러 메시지 표출을 위함
server:
  error:
    include-message: always

# 로그 레벨 설정
logging:
  level:
    com.oops.server: debug